# Generated by Django 5.2.11 on 2026-02-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Explicação do gabarito', null=True),
        ),
    ]
